calibration:
  ph:
    chan1:
      Tcal: !!python/unicode '21'
      a: !!python/unicode '7.00'
      b: !!python/unicode '4.00'
      date: 06/10/2019 15:33:29
    chan2:
      Tcal: !!python/unicode '21'
      a: !!python/unicode '7.00'
      b: !!python/unicode '4.00'
      date: 06/10/2019 15:33:31
    chan3:
      Tcal: !!python/unicode '21'
      a: !!python/unicode '7.00'
      b: !!python/unicode '4.00'
      date: 06/10/2019 15:33:26
    default_cal:
      ph1: 4.0
      ph2: 7.0
  temperature: !!python/unicode '25.01'
i2c:
  ph_channels:
    1: 64
    2: 65
    3: 67
  valves_islands:
    channels:
      1:
        CO2: FEFF
        N2: FDFF
      2:
        CO2: FBFF
        N2: F7FF
      3:
        CO2: EFFF
        N2: DFFF
      4:
        CO2: BFFF
        N2: 7FFF
      5:
        CO2: FFFE
        N2: FFFD
      6:
        CO2: FFFB
        N2: FFF7
    valves_addresses:
      1: 32
interface:
  ph_step: 2
  precision: 2
  temperatureDefault: 21.01
  temperatureMax: 50
  temperatureMin: 10
  time: hh:mm
  time_step: 60
os_integration:
  fifo_path: /tmp/pigrad_i2c_bus.fifo
